import 'package:csv/csv.dart';
import 'package:intl/intl.dart';
import '../models/delivery_model.dart';

/// Result of parsing CSV file
class CsvParseResult {
  final List<ParsedDelivery> validDeliveries;
  final List<ValidationError> errors;
  final List<ValidationWarning> warnings;

  CsvParseResult({
    required this.validDeliveries,
    required this.errors,
    required this.warnings,
  });

  bool get hasErrors => errors.isNotEmpty;
  bool get hasWarnings => warnings.isNotEmpty;
  bool get isValid => !hasErrors;
  int get totalRows => validDeliveries.length + errors.length;
}

/// Parsed delivery with original row number
class ParsedDelivery {
  final int rowNumber;
  final String customerName;
  final String customerAddress;
  final String? customerPhone;
  final String? customerNumber;
  final String? orderNumber;
  final String invoiceNumber;
  final DateTime? invoiceDate;
  final double? invoiceTotal;
  final double? taxAmount;
  final double? discountAmount;
  final DateTime scheduledDate;
  final String? driverEmail;
  final String? notes;
  final List<DeliveryItem> items;

  ParsedDelivery({
    required this.rowNumber,
    required this.customerName,
    required this.customerAddress,
    this.customerPhone,
    this.customerNumber,
    this.orderNumber,
  required this.invoiceNumber,
  this.invoiceDate,
    this.invoiceTotal,
    this.taxAmount,
    this.discountAmount,
    required this.scheduledDate,
    this.driverEmail,
    this.notes,
    required this.items,
  });

  /// Convert to Delivery model
  Delivery toDelivery({
    required String companyId,
    required String driverId,
  }) {
    return Delivery(
      id: '', // Will be generated by Firestore
      companyId: companyId,
      driverId: driverId,
      customerName: customerName,
      customerAddress: customerAddress,
      customerPhone: customerPhone,
      customerNumber: customerNumber,
      orderNumber: orderNumber,
      invoiceNumber: invoiceNumber,
      invoiceDate: invoiceDate,
      items: items,
      invoiceTotal: invoiceTotal,
      taxAmount: taxAmount,
      discountAmount: discountAmount,
      status: DeliveryStatus.pending,
      scheduledDate: scheduledDate,
      createdAt: DateTime.now(),
      notes: notes,
    );
  }
}

/// Validation error with row number and message
class ValidationError {
  final int rowNumber;
  final String field;
  final String message;

  ValidationError({
    required this.rowNumber,
    required this.field,
    required this.message,
  });

  @override
  String toString() => 'Row $rowNumber: $message';
}

/// Validation warning (non-critical)
class ValidationWarning {
  final int rowNumber;
  final String field;
  final String message;

  ValidationWarning({
    required this.rowNumber,
    required this.field,
    required this.message,
  });

  @override
  String toString() => 'Row $rowNumber: $message';
}

/// Service for parsing and validating CSV imports
class BulkImportService {
  /// Parse CSV content and validate
  static CsvParseResult parseCsv(String csvContent) {
    final validDeliveries = <ParsedDelivery>[];
    final errors = <ValidationError>[];
    final warnings = <ValidationWarning>[];

    try {
      // Parse CSV
      final rows = const CsvToListConverter().convert(csvContent);

      if (rows.isEmpty) {
        errors.add(ValidationError(
          rowNumber: 0,
          field: 'file',
          message: 'CSV file is empty',
        ));
        return CsvParseResult(
          validDeliveries: [],
          errors: errors,
          warnings: [],
        );
      }

      // Get headers from first row
      final headers = rows[0].map((e) => e.toString().trim()).toList();

      // Validate required columns
      final requiredColumns = [
        'customerName',
        'customerAddress',
          'invoiceNumber',
        'scheduledDate',
      ];

      for (var column in requiredColumns) {
        if (!headers.contains(column)) {
          errors.add(ValidationError(
            rowNumber: 0,
            field: 'headers',
            message: 'Missing required column: $column',
          ));
        }
      }

      if (errors.isNotEmpty) {
        return CsvParseResult(
          validDeliveries: [],
          errors: errors,
          warnings: [],
        );
      }

      // Parse data rows (skip header row)
      for (var i = 1; i < rows.length; i++) {
        final row = rows[i];
        final rowNumber = i + 1; // +1 for Excel row number (1-based)

        // Skip empty rows
        if (row.every((cell) => cell == null || cell.toString().trim().isEmpty)) {
          continue;
        }

        try {
          final rowData = <String, dynamic>{};
          for (var j = 0; j < headers.length && j < row.length; j++) {
            rowData[headers[j]] = row[j];
          }

          // Validate and parse row
          final parsed = _parseRow(rowNumber, rowData, errors, warnings);
          if (parsed != null) {
            validDeliveries.add(parsed);
          }
        } catch (e) {
          errors.add(ValidationError(
            rowNumber: rowNumber,
            field: 'row',
            message: 'Error parsing row: $e',
          ));
        }
      }
    } catch (e) {
      errors.add(ValidationError(
        rowNumber: 0,
        field: 'file',
        message: 'Error parsing CSV: $e',
      ));
    }

    return CsvParseResult(
      validDeliveries: validDeliveries,
      errors: errors,
      warnings: warnings,
    );
  }

  /// Parse single row
  static ParsedDelivery? _parseRow(
    int rowNumber,
    Map<String, dynamic> rowData,
    List<ValidationError> errors,
    List<ValidationWarning> warnings,
  ) {
    // Get values
    final customerName = rowData['customerName']?.toString().trim() ?? '';
    final customerAddress = rowData['customerAddress']?.toString().trim() ?? '';
    final customerPhone = rowData['customerPhone']?.toString().trim();
    final customerNumber = rowData['customerNumber']?.toString().trim();
    final orderNumber = rowData['orderNumber']?.toString().trim();
    final invoiceNumber = rowData['invoiceNumber']?.toString().trim() ?? '';
    final invoiceDateStr = rowData['invoiceDate']?.toString().trim();
    final invoiceTotalStr = rowData['invoiceTotal']?.toString().trim();
    final taxAmountStr = rowData['taxAmount']?.toString().trim();
    final discountAmountStr = rowData['discountAmount']?.toString().trim();
    final scheduledDateStr = rowData['scheduledDate']?.toString().trim() ?? '';
    final driverEmail = rowData['driverEmail']?.toString().trim();
    final notes = rowData['notes']?.toString().trim();

    var hasError = false;

    // Validate required fields
    if (customerName.isEmpty) {
      errors.add(ValidationError(
        rowNumber: rowNumber,
        field: 'customerName',
        message: 'Customer name is required',
      ));
      hasError = true;
    }

    if (customerAddress.isEmpty) {
      errors.add(ValidationError(
        rowNumber: rowNumber,
        field: 'customerAddress',
        message: 'Customer address is required',
      ));
      hasError = true;
    }

    if (invoiceNumber.isEmpty) {
      errors.add(ValidationError(
        rowNumber: rowNumber,
        field: 'invoiceNumber',
        message: 'Invoice number is required',
      ));
      hasError = true;
    }

    // Parse and validate date
    DateTime? scheduledDate;
    // Parse invoice date (optional)
    DateTime? invoiceDate;
    if (invoiceDateStr != null && invoiceDateStr.isNotEmpty) {
      invoiceDate = _parseDate(invoiceDateStr);
      if (invoiceDate == null) {
        errors.add(ValidationError(
          rowNumber: rowNumber,
          field: 'invoiceDate',
          message: 'Invalid invoice date format. Use YYYY-MM-DD (e.g., 2025-10-20), DD/MM/YYYY, or MM/DD/YYYY',
        ));
        hasError = true;
      }
    }
    if (scheduledDateStr.isEmpty) {
      errors.add(ValidationError(
        rowNumber: rowNumber,
        field: 'scheduledDate',
        message: 'Scheduled date is required',
      ));
      hasError = true;
    } else {
      // Try multiple date formats
      scheduledDate = _parseDate(scheduledDateStr);
      
      if (scheduledDate == null) {
        errors.add(ValidationError(
          rowNumber: rowNumber,
          field: 'scheduledDate',
          message: 'Invalid date format. Use YYYY-MM-DD (e.g., 2025-10-20), DD/MM/YYYY, or MM/DD/YYYY',
        ));
        hasError = true;
      } else {
        // Warn if date is in the past
        if (scheduledDate.isBefore(DateTime.now().subtract(const Duration(days: 1)))) {
          warnings.add(ValidationWarning(
            rowNumber: rowNumber,
            field: 'scheduledDate',
            message: 'Scheduled date is in the past',
          ));
        }
      }
    }

    // Parse monetary fields
    double? invoiceTotal;
    double? taxAmount;
    double? discountAmount;

    if (invoiceTotalStr != null && invoiceTotalStr.isNotEmpty) {
      try {
        invoiceTotal = double.parse(invoiceTotalStr);
        if (invoiceTotal < 0) {
          warnings.add(ValidationWarning(
            rowNumber: rowNumber,
            field: 'invoiceTotal',
            message: 'Invoice total should not be negative',
          ));
        }
      } catch (e) {
        warnings.add(ValidationWarning(
          rowNumber: rowNumber,
          field: 'invoiceTotal',
          message: 'Invalid invoice total format (expected number)',
        ));
      }
    }

    if (taxAmountStr != null && taxAmountStr.isNotEmpty) {
      try {
        taxAmount = double.parse(taxAmountStr);
        if (taxAmount < 0) {
          warnings.add(ValidationWarning(
            rowNumber: rowNumber,
            field: 'taxAmount',
            message: 'Tax amount should not be negative',
          ));
        }
      } catch (e) {
        warnings.add(ValidationWarning(
          rowNumber: rowNumber,
          field: 'taxAmount',
          message: 'Invalid tax amount format (expected number)',
        ));
      }
    }

    if (discountAmountStr != null && discountAmountStr.isNotEmpty) {
      try {
        discountAmount = double.parse(discountAmountStr);
        if (discountAmount < 0) {
          warnings.add(ValidationWarning(
            rowNumber: rowNumber,
            field: 'discountAmount',
            message: 'Discount amount should not be negative',
          ));
        }
      } catch (e) {
        warnings.add(ValidationWarning(
          rowNumber: rowNumber,
          field: 'discountAmount',
          message: 'Invalid discount amount format (expected number)',
        ));
      }
    }

    // Parse items (up to 10 items)
    final items = <DeliveryItem>[];
    for (var i = 1; i <= 10; i++) {
      final description = rowData['item${i}_description']?.toString().trim() ?? '';
      final quantityStr = rowData['item${i}_quantity']?.toString().trim() ?? '';
      final unit = rowData['item${i}_unit']?.toString().trim();
      final unitPriceStr = rowData['item${i}_unitPrice']?.toString().trim();
      final totalPriceStr = rowData['item${i}_totalPrice']?.toString().trim();

      if (description.isNotEmpty) {
        // Parse quantity
        double? quantity;
        if (quantityStr.isNotEmpty) {
          try {
            quantity = double.parse(quantityStr);
            if (quantity <= 0) {
              errors.add(ValidationError(
                rowNumber: rowNumber,
                field: 'item${i}_quantity',
                message: 'Item $i quantity must be greater than 0',
              ));
              hasError = true;
            }
          } catch (e) {
            errors.add(ValidationError(
              rowNumber: rowNumber,
              field: 'item${i}_quantity',
              message: 'Item $i quantity must be a number',
            ));
            hasError = true;
          }
        } else {
          quantity = 1.0; // Default quantity
        }

        // Parse unit price
        double? unitPrice;
        if (unitPriceStr != null && unitPriceStr.isNotEmpty) {
          try {
            unitPrice = double.parse(unitPriceStr);
            if (unitPrice < 0) {
              warnings.add(ValidationWarning(
                rowNumber: rowNumber,
                field: 'item${i}_unitPrice',
                message: 'Item $i unit price should not be negative',
              ));
            }
          } catch (e) {
            warnings.add(ValidationWarning(
              rowNumber: rowNumber,
              field: 'item${i}_unitPrice',
              message: 'Item $i unit price has invalid format (expected number)',
            ));
          }
        }

        // Parse total price
        double? totalPrice;
        if (totalPriceStr != null && totalPriceStr.isNotEmpty) {
          try {
            totalPrice = double.parse(totalPriceStr);
            if (totalPrice < 0) {
              warnings.add(ValidationWarning(
                rowNumber: rowNumber,
                field: 'item${i}_totalPrice',
                message: 'Item $i total price should not be negative',
              ));
            }
          } catch (e) {
            warnings.add(ValidationWarning(
              rowNumber: rowNumber,
              field: 'item${i}_totalPrice',
              message: 'Item $i total price has invalid format (expected number)',
            ));
          }
        }

        if (quantity != null && quantity > 0) {
          items.add(DeliveryItem(
            description: description,
            quantity: quantity,
            unit: unit,
            unitPrice: unitPrice,
            totalPrice: totalPrice,
          ));
        }
      }
    }

    // Warn if no items
    if (items.isEmpty) {
      warnings.add(ValidationWarning(
        rowNumber: rowNumber,
        field: 'items',
        message: 'No items specified for this delivery',
      ));
    }

    // Return null if has errors
    if (hasError || scheduledDate == null) {
      return null;
    }

    return ParsedDelivery(
      rowNumber: rowNumber,
      customerName: customerName,
      customerAddress: customerAddress,
      customerPhone: customerPhone?.isNotEmpty == true ? customerPhone : null,
      customerNumber: customerNumber?.isNotEmpty == true ? customerNumber : null,
      orderNumber: orderNumber?.isNotEmpty == true ? orderNumber : null,
  invoiceNumber: invoiceNumber,
  invoiceDate: invoiceDate,
      invoiceTotal: invoiceTotal,
      taxAmount: taxAmount,
      discountAmount: discountAmount,
      scheduledDate: scheduledDate,
      driverEmail: driverEmail?.isNotEmpty == true ? driverEmail : null,
      notes: notes?.isNotEmpty == true ? notes : null,
      items: items,
    );
  }

  /// Check for duplicate invoice numbers
  static List<ValidationError> checkDuplicateInvoices(
    List<ParsedDelivery> deliveries,
  ) {
    final errors = <ValidationError>[];
    final seenInvoices = <String, int>{};

    for (var delivery in deliveries) {
      final invoice = delivery.invoiceNumber.toLowerCase();
      if (seenInvoices.containsKey(invoice)) {
        errors.add(ValidationError(
          rowNumber: delivery.rowNumber,
          field: 'invoiceNumber',
          message: 'Duplicate invoice number: ${delivery.invoiceNumber} (also in row ${seenInvoices[invoice]})',
        ));
      } else {
        seenInvoices[invoice] = delivery.rowNumber;
      }
    }

    return errors;
  }

  /// Parse date from string, supporting multiple formats
  static DateTime? _parseDate(String dateStr) {
    final formats = [
      'yyyy-MM-dd',      // 2025-10-20 (ISO format - preferred)
      'dd/MM/yyyy',      // 20/10/2025 (European format)
      'MM/dd/yyyy',      // 10/20/2025 (US format)
      'dd-MM-yyyy',      // 20-10-2025
      'yyyy/MM/dd',      // 2025/10/20
      'd/M/yyyy',        // 20/10/2025 (single digits)
      'M/d/yyyy',        // 10/20/2025 (single digits)
    ];

    for (var format in formats) {
      try {
        return DateFormat(format).parseStrict(dateStr);
      } catch (_) {
        // Try next format
      }
    }

    return null;
  }
}
