import '../services/bulk_import_service.dart';
import 'delivery_model.dart';

/// Editable wrapper around ParsedDelivery for UI editing
class EditableDelivery {
  final int rowNumber;
  
  // Editable fields
  String customerName;
  String customerAddress;
  String? customerPhone;
  String? customerNumber;
  String? orderNumber;
  String invoiceNumber;
  DateTime? invoiceDate;
  double? invoiceTotal;
  double? taxAmount;
  double? discountAmount;
  DateTime scheduledDate;
  String? driverEmail;
  String? notes;
  List<DeliveryItem> items;

  // UI state
  bool isSelected;
  bool isRemoved;
  bool isEdited;
  List<ValidationError> errors;
  List<ValidationWarning> warnings;

  EditableDelivery({
    required this.rowNumber,
    required this.customerName,
    required this.customerAddress,
    this.customerPhone,
    this.customerNumber,
    this.orderNumber,
    required this.invoiceNumber,
    this.invoiceDate,
    this.invoiceTotal,
    this.taxAmount,
    this.discountAmount,
    required this.scheduledDate,
    this.driverEmail,
    this.notes,
    required this.items,
    this.isSelected = true,
    this.isRemoved = false,
    this.isEdited = false,
    this.errors = const [],
    this.warnings = const [],
  });

  /// Create from ParsedDelivery
  factory EditableDelivery.fromParsed(ParsedDelivery parsed) {
    return EditableDelivery(
      rowNumber: parsed.rowNumber,
      customerName: parsed.customerName,
      customerAddress: parsed.customerAddress,
      customerPhone: parsed.customerPhone,
      customerNumber: parsed.customerNumber,
      orderNumber: parsed.orderNumber,
      invoiceNumber: parsed.invoiceNumber,
      invoiceDate: parsed.invoiceDate,
      invoiceTotal: parsed.invoiceTotal,
      taxAmount: parsed.taxAmount,
      discountAmount: parsed.discountAmount,
      scheduledDate: parsed.scheduledDate,
      driverEmail: parsed.driverEmail,
      notes: parsed.notes,
      items: List.from(parsed.items),
    );
  }

  /// Convert to Delivery model
  Delivery toDelivery({
    required String companyId,
    required String driverId,
  }) {
    return Delivery(
      id: '', // Will be generated by Firestore
      companyId: companyId,
      driverId: driverId,
      customerName: customerName,
      customerAddress: customerAddress,
      customerPhone: customerPhone,
      customerNumber: customerNumber,
      orderNumber: orderNumber,
      invoiceNumber: invoiceNumber,
      invoiceDate: invoiceDate,
      items: items,
      invoiceTotal: invoiceTotal,
      taxAmount: taxAmount,
      discountAmount: discountAmount,
      status: DeliveryStatus.pending,
      scheduledDate: scheduledDate,
      createdAt: DateTime.now(),
      notes: notes,
    );
  }

  /// Validate current data
  void validate({List<String>? existingInvoices, List<EditableDelivery>? allDeliveries}) {
    errors = [];
    warnings = [];

    // Required fields
    if (customerName.trim().isEmpty) {
      errors.add(ValidationError(
        rowNumber: rowNumber,
        field: 'customerName',
        message: 'Customer name is required',
      ));
    }

    if (customerAddress.trim().isEmpty) {
      errors.add(ValidationError(
        rowNumber: rowNumber,
        field: 'customerAddress',
        message: 'Customer address is required',
      ));
    }

    if (invoiceNumber.trim().isEmpty) {
      errors.add(ValidationError(
        rowNumber: rowNumber,
        field: 'invoiceNumber',
        message: 'Invoice number is required',
      ));
    } else {
      // Check for duplicates in database
      if (existingInvoices != null && existingInvoices.contains(invoiceNumber)) {
        errors.add(ValidationError(
          rowNumber: rowNumber,
          field: 'invoiceNumber',
          message: 'Invoice number already exists in database',
        ));
      }
      
      // Check for duplicates in current batch
      if (allDeliveries != null) {
        final duplicates = allDeliveries.where(
          (d) => d != this && !d.isRemoved && d.invoiceNumber == invoiceNumber,
        );
        if (duplicates.isNotEmpty) {
          errors.add(ValidationError(
            rowNumber: rowNumber,
            field: 'invoiceNumber',
            message: 'Duplicate invoice number in rows: ${duplicates.map((d) => d.rowNumber).join(", ")}',
          ));
        }
      }
    }

    // Warnings
    if (customerPhone == null || customerPhone!.trim().isEmpty) {
      warnings.add(ValidationWarning(
        rowNumber: rowNumber,
        field: 'customerPhone',
        message: 'No customer phone number',
      ));
    }

    if (driverEmail == null || driverEmail!.trim().isEmpty) {
      warnings.add(ValidationWarning(
        rowNumber: rowNumber,
        field: 'driverEmail',
        message: 'No driver assigned - will be marked as unassigned',
      ));
    }

    if (items.isEmpty) {
      warnings.add(ValidationWarning(
        rowNumber: rowNumber,
        field: 'items',
        message: 'No line items',
      ));
    }
  }

  bool get hasErrors => errors.isNotEmpty;
  bool get hasWarnings => warnings.isNotEmpty;
  bool get isValid => !hasErrors && !isRemoved;
}
