import 'package:csv/csv.dart';
import '../models/customer_model.dart';

/// Result of CSV parsing
class CustomerImportResult {
  final List<ParsedCustomer> validCustomers;
  final List<ImportError> errors;
  final List<ImportWarning> warnings;

  CustomerImportResult({
    required this.validCustomers,
    required this.errors,
    required this.warnings,
  });

  bool get hasErrors => errors.isNotEmpty;
  bool get hasWarnings => warnings.isNotEmpty;
  bool get isValid => !hasErrors;
  int get totalRows => validCustomers.length + errors.length;
  int get validCount => validCustomers.length;
  int get errorCount => errors.length;
}

/// Parsed customer with row number
class ParsedCustomer {
  final int rowNumber;
  final String customerNumber;
  final String name;
  final String address;
  final String? contactPerson;
  final String? phone;
  final String? email;
  final String? deliveryInstructions;
  final String? accountNumber;
  final CustomerType customerType;
  final List<String> tags;
  final bool isActive;

  ParsedCustomer({
    required this.rowNumber,
    required this.customerNumber,
    required this.name,
    required this.address,
    this.contactPerson,
    this.phone,
    this.email,
    this.deliveryInstructions,
    this.accountNumber,
    this.customerType = CustomerType.business,
    this.tags = const [],
    this.isActive = true,
  });

  /// Convert to Customer model
  Customer toCustomer({required String companyId}) {
    return Customer(
      id: '', // Will be generated by Firestore
      companyId: companyId,
      customerNumber: customerNumber,
      name: name,
      address: address,
      contactPerson: contactPerson,
      phone: phone,
      email: email,
      deliveryInstructions: deliveryInstructions,
      accountNumber: accountNumber,
      customerType: customerType,
      tags: tags,
      isActive: isActive,
    );
  }
}

/// Import error
class ImportError {
  final int rowNumber;
  final String field;
  final String message;

  ImportError({
    required this.rowNumber,
    required this.field,
    required this.message,
  });

  @override
  String toString() => 'Row $rowNumber, $field: $message';
}

/// Import warning
class ImportWarning {
  final int rowNumber;
  final String field;
  final String message;

  ImportWarning({
    required this.rowNumber,
    required this.field,
    required this.message,
  });

  @override
  String toString() => 'Row $rowNumber, $field: $message';
}

/// Service for importing customers from CSV
class CustomerImportService {
  /// Parse CSV content and validate
  static CustomerImportResult parseCsv(String csvContent) {
    final validCustomers = <ParsedCustomer>[];
    final errors = <ImportError>[];
    final warnings = <ImportWarning>[];

    try {
      // Parse CSV
      final rows = const CsvToListConverter().convert(
        csvContent,
        eol: '\n',
        shouldParseNumbers: false,
      );

      if (rows.isEmpty) {
        errors.add(ImportError(
          rowNumber: 0,
          field: 'File',
          message: 'CSV file is empty',
        ));
        return CustomerImportResult(
          validCustomers: validCustomers,
          errors: errors,
          warnings: warnings,
        );
      }

      // Get headers (first row)
      final headers = rows.first.map((e) => e.toString().trim().toLowerCase()).toList();
      
      // Validate required headers
      final requiredHeaders = {
        'customer number': ['customernumber', 'customer number', 'number', 'customer_number'],
        'customer name': ['customername', 'customer name', 'name', 'customer_name'],
        'address': ['address', 'deliveryaddress', 'delivery address', 'delivery_address'],
      };
      
      for (final entry in requiredHeaders.entries) {
        final displayName = entry.key;
        final possibleNames = entry.value;
        
        // Check if any header matches any possible name
        final found = headers.any((header) {
          final normalizedHeader = header.replaceAll(' ', '').replaceAll('_', '');
          return possibleNames.any((possible) => 
            normalizedHeader == possible.replaceAll(' ', '').replaceAll('_', '')
          );
        });
        
        if (!found) {
          errors.add(ImportError(
            rowNumber: 1,
            field: 'Headers',
            message: 'Missing required column: $displayName',
          ));
        }
      }

      if (errors.isNotEmpty) {
        return CustomerImportResult(
          validCustomers: validCustomers,
          errors: errors,
          warnings: warnings,
        );
      }

      // Find column indexes
      final customerNumberIndex = _findColumnIndex(headers, ['customernumber', 'customer number', 'number', 'code']);
      final nameIndex = _findColumnIndex(headers, ['customername', 'customer name', 'name']);
      final addressIndex = _findColumnIndex(headers, ['address', 'deliveryaddress', 'delivery address']);
      final contactPersonIndex = _findColumnIndex(headers, ['contactperson', 'contact person', 'contact']);
      final phoneIndex = _findColumnIndex(headers, ['phone', 'phonenumber', 'phone number', 'telephone']);
      final emailIndex = _findColumnIndex(headers, ['email', 'e-mail']);
      final instructionsIndex = _findColumnIndex(headers, ['deliveryinstructions', 'delivery instructions', 'instructions', 'notes']);
      final accountNumberIndex = _findColumnIndex(headers, ['accountnumber', 'account number', 'account', 'acc']);
      final customerTypeIndex = _findColumnIndex(headers, ['customertype', 'customer type', 'type']);
      final tagsIndex = _findColumnIndex(headers, ['tags', 'categories']);
      final activeIndex = _findColumnIndex(headers, ['active', 'isactive', 'status']);

      // Parse data rows (skip header)
      for (int i = 1; i < rows.length; i++) {
        final row = rows[i];
        final rowNumber = i + 1;

        // Skip empty rows
        if (row.every((cell) => cell.toString().trim().isEmpty)) {
          continue;
        }

        try {
          // Get required fields
          final customerNumber = _getCell(row, customerNumberIndex)?.trim() ?? '';
          final name = _getCell(row, nameIndex)?.trim() ?? '';
          final address = _getCell(row, addressIndex)?.trim() ?? '';

          // Validate required fields
          final rowErrors = <ImportError>[];
          
          if (customerNumber.isEmpty) {
            rowErrors.add(ImportError(
              rowNumber: rowNumber,
              field: 'Customer Number',
              message: 'Customer number is required',
            ));
          }

          if (name.isEmpty) {
            rowErrors.add(ImportError(
              rowNumber: rowNumber,
              field: 'Customer Name',
              message: 'Customer name is required',
            ));
          }

          if (address.isEmpty) {
            rowErrors.add(ImportError(
              rowNumber: rowNumber,
              field: 'Address',
              message: 'Address is required',
            ));
          }

          if (rowErrors.isNotEmpty) {
            errors.addAll(rowErrors);
            continue;
          }

          // Get optional fields
          final contactPerson = _getCell(row, contactPersonIndex)?.trim();
          final phone = _getCell(row, phoneIndex)?.trim();
          final email = _getCell(row, emailIndex)?.trim();
          final instructions = _getCell(row, instructionsIndex)?.trim();
          final accountNumber = _getCell(row, accountNumberIndex)?.trim();
          
          // Parse customer type
          final typeStr = _getCell(row, customerTypeIndex)?.trim().toLowerCase();
          CustomerType customerType = CustomerType.business;
          if (typeStr == 'residential' || typeStr == 'resident' || typeStr == 'res') {
            customerType = CustomerType.residential;
          }

          // Parse tags
          final tagsStr = _getCell(row, tagsIndex)?.trim() ?? '';
          final tags = tagsStr.isNotEmpty 
              ? tagsStr.split(',').map((t) => t.trim()).where((t) => t.isNotEmpty).toList()
              : <String>[];

          // Parse active status
          final activeStr = _getCell(row, activeIndex)?.trim().toLowerCase();
          final isActive = activeStr != 'false' && activeStr != 'no' && activeStr != '0';

          // Validate email format (warning only)
          if (email != null && email.isNotEmpty && !_isValidEmail(email)) {
            warnings.add(ImportWarning(
              rowNumber: rowNumber,
              field: 'Email',
              message: 'Email format may be invalid: $email',
            ));
          }

          // Create parsed customer
          validCustomers.add(ParsedCustomer(
            rowNumber: rowNumber,
            customerNumber: customerNumber,
            name: name,
            address: address,
            contactPerson: contactPerson,
            phone: phone,
            email: email,
            deliveryInstructions: instructions,
            accountNumber: accountNumber,
            customerType: customerType,
            tags: tags,
            isActive: isActive,
          ));

        } catch (e) {
          errors.add(ImportError(
            rowNumber: rowNumber,
            field: 'Row',
            message: 'Error parsing row: $e',
          ));
        }
      }

    } catch (e) {
      errors.add(ImportError(
        rowNumber: 0,
        field: 'File',
        message: 'Error parsing CSV: $e',
      ));
    }

    return CustomerImportResult(
      validCustomers: validCustomers,
      errors: errors,
      warnings: warnings,
    );
  }

  /// Check for duplicate customer numbers in parsed data
  static List<ImportError> checkDuplicates(List<ParsedCustomer> customers) {
    final errors = <ImportError>[];
    final seen = <String, int>{};

    for (final customer in customers) {
      final number = customer.customerNumber.toLowerCase();
      if (seen.containsKey(number)) {
        errors.add(ImportError(
          rowNumber: customer.rowNumber,
          field: 'Customer Number',
          message: 'Duplicate customer number: ${customer.customerNumber} (also in row ${seen[number]})',
        ));
      } else {
        seen[number] = customer.rowNumber;
      }
    }

    return errors;
  }

  /// Check if customer numbers already exist in database
  static List<ImportError> checkExistingCustomers(
    List<ParsedCustomer> customers,
    List<Customer> existingCustomers,
  ) {
    final errors = <ImportError>[];
    final existingNumbers = existingCustomers
        .map((c) => c.customerNumber.toLowerCase())
        .toSet();

    for (final customer in customers) {
      if (existingNumbers.contains(customer.customerNumber.toLowerCase())) {
        errors.add(ImportError(
          rowNumber: customer.rowNumber,
          field: 'Customer Number',
          message: 'Customer number already exists: ${customer.customerNumber}',
        ));
      }
    }

    return errors;
  }

  /// Generate CSV template
  static String generateTemplate() {
    const headers = [
      'Customer Number*',
      'Customer Name*',
      'Address*',
      'Contact Person',
      'Phone',
      'Email',
      'Delivery Instructions',
      'Account Number',
      'Customer Type',
      'Tags',
      'Active',
    ];

    const exampleRows = [
      [
        'BOX001',
        'Boxer Superstore',
        '123 Main St, Miami, FL 33101',
        'John Manager',
        '305-555-0100',
        'john@boxersuper.com',
        'Ring bell at loading dock. Gate code: 1234',
        'ACC-1001',
        'business',
        'VIP,Weekly',
        'TRUE',
      ],
      [
        'ACME999',
        'ACME Corporation',
        '789 Business Blvd, Miami, FL 33103',
        'Sarah Smith',
        '305-555-0200',
        'sarah@acme.com',
        'Call 30 min before arrival',
        'ACC-2002',
        'business',
        'Wholesale',
        'TRUE',
      ],
      [
        'RES001',
        'John Doe Residence',
        '321 Oak Ave, Miami, FL 33104',
        'John Doe',
        '305-555-0300',
        'johndoe@email.com',
        'Leave at front door if no answer',
        '',
        'residential',
        'Residential',
        'TRUE',
      ],
    ];

    final List<List<dynamic>> csvData = [headers, ...exampleRows];
    return const ListToCsvConverter().convert(csvData);
  }

  // Helper methods

  static int _findColumnIndex(List<String> headers, List<String> possibleNames) {
    for (int i = 0; i < headers.length; i++) {
      final header = headers[i].replaceAll(' ', '').replaceAll('_', '').toLowerCase();
      for (final name in possibleNames) {
        if (header.contains(name.replaceAll(' ', ''))) {
          return i;
        }
      }
    }
    return -1;
  }

  static String? _getCell(List row, int index) {
    if (index < 0 || index >= row.length) return null;
    final value = row[index]?.toString();
    return value?.isEmpty == true ? null : value;
  }

  static bool _isValidEmail(String email) {
    return RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$').hasMatch(email);
  }
}
