import '../services/customer_import_service.dart';
import 'customer_model.dart';

/// Editable wrapper around ParsedCustomer for UI editing
class EditableCustomer {
  final int rowNumber;
  
  // Editable fields
  String customerNumber;
  String name;
  String address;
  String? contactPerson;
  String? phone;
  String? email;
  String? deliveryInstructions;
  String? accountNumber;
  CustomerType customerType;
  List<String> tags;
  bool isActive;

  // UI state
  bool isSelected;
  bool isRemoved;
  bool isEdited;
  List<ImportError> errors;
  List<ImportWarning> warnings;

  EditableCustomer({
    required this.rowNumber,
    required this.customerNumber,
    required this.name,
    required this.address,
    this.contactPerson,
    this.phone,
    this.email,
    this.deliveryInstructions,
    this.accountNumber,
    this.customerType = CustomerType.business,
    this.tags = const [],
    this.isActive = true,
    this.isSelected = true,
    this.isRemoved = false,
    this.isEdited = false,
    this.errors = const [],
    this.warnings = const [],
  });

  /// Create from ParsedCustomer
  factory EditableCustomer.fromParsed(ParsedCustomer parsed) {
    return EditableCustomer(
      rowNumber: parsed.rowNumber,
      customerNumber: parsed.customerNumber,
      name: parsed.name,
      address: parsed.address,
      contactPerson: parsed.contactPerson,
      phone: parsed.phone,
      email: parsed.email,
      deliveryInstructions: parsed.deliveryInstructions,
      accountNumber: parsed.accountNumber,
      customerType: parsed.customerType,
      tags: List.from(parsed.tags),
      isActive: parsed.isActive,
    );
  }

  /// Convert to Customer model
  Customer toCustomer({required String companyId}) {
    return Customer(
      id: '', // Will be generated by Firestore
      companyId: companyId,
      customerNumber: customerNumber,
      name: name,
      address: address,
      contactPerson: contactPerson,
      phone: phone,
      email: email,
      deliveryInstructions: deliveryInstructions,
      accountNumber: accountNumber,
      customerType: customerType,
      tags: tags,
      isActive: isActive,
    );
  }

  /// Validate current data
  void validate({List<String>? existingNumbers, List<EditableCustomer>? allCustomers}) {
    errors = [];
    warnings = [];

    // Required fields
    if (customerNumber.trim().isEmpty) {
      errors.add(ImportError(
        rowNumber: rowNumber,
        field: 'customerNumber',
        message: 'Customer number is required',
      ));
    } else {
      // Check for duplicates in database
      if (existingNumbers != null && existingNumbers.contains(customerNumber)) {
        errors.add(ImportError(
          rowNumber: rowNumber,
          field: 'customerNumber',
          message: 'Customer number already exists',
        ));
      }
      
      // Check for duplicates in current batch
      if (allCustomers != null) {
        final duplicates = allCustomers.where(
          (d) => d != this && !d.isRemoved && d.customerNumber == customerNumber,
        );
        if (duplicates.isNotEmpty) {
          errors.add(ImportError(
            rowNumber: rowNumber,
            field: 'customerNumber',
            message: 'Duplicate customer number in rows: ${duplicates.map((d) => d.rowNumber).join(", ")}',
          ));
        }
      }
    }

    if (name.trim().isEmpty) {
      errors.add(ImportError(
        rowNumber: rowNumber,
        field: 'name',
        message: 'Customer name is required',
      ));
    }

    if (address.trim().isEmpty) {
      errors.add(ImportError(
        rowNumber: rowNumber,
        field: 'address',
        message: 'Address is required',
      ));
    }

    // Warnings
    if (phone == null || phone!.trim().isEmpty) {
      warnings.add(ImportWarning(
        rowNumber: rowNumber,
        field: 'phone',
        message: 'No phone number provided',
      ));
    }

    if (email == null || email!.trim().isEmpty) {
      warnings.add(ImportWarning(
        rowNumber: rowNumber,
        field: 'email',
        message: 'No email provided',
      ));
    }
  }

  bool get hasErrors => errors.isNotEmpty;
  bool get hasWarnings => warnings.isNotEmpty;
  bool get isValid => !hasErrors && !isRemoved;
}
