// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAag-zEb2paO6eFStgNPInP4Teet36k8jM',
    appId: '1:526380867753:web:f4b6074b528c7c86c889b8',
    messagingSenderId: '526380867753',
    projectId: 'podsafe-production',
    authDomain: 'podsafe-production.firebaseapp.com',
    storageBucket: 'podsafe-production.firebasestorage.app',
    measurementId: 'G-1RGTKG7CG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAQasW3BFJ861JGAVbtODe5WhgCS12Jso',
    appId: '1:526380867753:android:16c688d5b07f3478c889b8',
    messagingSenderId: '526380867753',
    projectId: 'podsafe-production',
    storageBucket: 'podsafe-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUlUF4FMrJX0JXeIkldveF1eMI6zzRdAI',
    appId: '1:526380867753:ios:50aaddf694ebc3f0c889b8',
    messagingSenderId: '526380867753',
    projectId: 'podsafe-production',
    storageBucket: 'podsafe-production.firebasestorage.app',
    iosBundleId: 'com.example.podsafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUlUF4FMrJX0JXeIkldveF1eMI6zzRdAI',
    appId: '1:526380867753:ios:50aaddf694ebc3f0c889b8',
    messagingSenderId: '526380867753',
    projectId: 'podsafe-production',
    storageBucket: 'podsafe-production.firebasestorage.app',
    iosBundleId: 'com.example.podsafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAag-zEb2paO6eFStgNPInP4Teet36k8jM',
    appId: '1:526380867753:web:6094e1ccbbc2681ac889b8',
    messagingSenderId: '526380867753',
    projectId: 'podsafe-production',
    authDomain: 'podsafe-production.firebaseapp.com',
    storageBucket: 'podsafe-production.firebasestorage.app',
    measurementId: 'G-EP7J9D1WJB',
  );
}
