// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        // Use web config for Windows desktop
        return web;
      case TargetPlatform.linux:
        // Use web config for Linux desktop
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQTPiBCb104C5ROKYf0xvNR8vaR0m_GjQ',
    appId: '1:143672681817:web:69c7df3f67b40552955848',
    messagingSenderId: '143672681817',
    projectId: 'podsafe-92a3e',
    authDomain: 'podsafe-92a3e.firebaseapp.com',
    storageBucket: 'podsafe-92a3e.firebasestorage.app',
    measurementId: 'G-PZQ9KM02G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYvRnk_iXCrZf_svnOSsd9vnCO-yOZQBw',
    appId: '1:143672681817:android:7e64299613a0a1f2955848',
    messagingSenderId: '143672681817',
    projectId: 'podsafe-92a3e',
    storageBucket: 'podsafe-92a3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQTPiBCb104C5ROKYf0xvNR8vaR0m_GjQ',
    appId: '1:143672681817:ios:1a94e6d4e4ae1f99955848',
    messagingSenderId: '143672681817',
    projectId: 'podsafe-92a3e',
    storageBucket: 'podsafe-92a3e.firebasestorage.app',
    iosClientId: 'com.example.podsafe',
    iosBundleId: 'com.example.podsafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQTPiBCb104C5ROKYf0xvNR8vaR0m_GjQ',
    appId: '1:143672681817:ios:1a94e6d4e4ae1f99955848',
    messagingSenderId: '143672681817',
    projectId: 'podsafe-92a3e',
    storageBucket: 'podsafe-92a3e.firebasestorage.app',
    iosClientId: 'com.example.podsafe',
    iosBundleId: 'com.example.podsafe',
  );
}