import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import '../../utils/theme.dart';
import '../../providers/auth_provider.dart';
import '../../providers/catalog_provider.dart';
import '../../models/catalog_item_model.dart';

class BulkItemCreationScreen extends StatefulWidget {
  const BulkItemCreationScreen({super.key});

  @override
  State<BulkItemCreationScreen> createState() => _BulkItemCreationScreenState();
}

class EditableItem {
  int rowNumber;
  String description;
  String? sku;
  ItemCategory category;
  String? unit;
  double? defaultQuantity;
  double? unitPrice;
  
  bool isSelected;
  bool isRemoved;
  bool isEdited;
  List<ItemValidationError> errors;
  List<ItemValidationWarning> warnings;

  EditableItem({
    required this.rowNumber,
    required this.description,
    this.sku,
    required this.category,
    this.unit,
    this.defaultQuantity,
    this.unitPrice,
    this.isSelected = false,
    this.isRemoved = false,
    this.isEdited = false,
    this.errors = const [],
    this.warnings = const [],
  });

  bool get isValid => errors.isEmpty;
  bool get hasErrors => errors.isNotEmpty;
  bool get hasWarnings => warnings.isNotEmpty;

  void validate({List<String> existingSKUs = const []}) {
    errors.clear();
    warnings.clear();

    // Required: Description
    if (description.trim().isEmpty) {
      errors.add(ItemValidationError('description', 'Description is required'));
    }

    // Optional: SKU - check for duplicates
    if (sku != null && sku!.isNotEmpty) {
      if (existingSKUs.contains(sku)) {
        warnings.add(ItemValidationWarning('sku', 'This SKU already exists in catalog'));
      }
    }

    // Optional: Unit - warn if missing
    if (unit == null || unit!.isEmpty) {
      warnings.add(ItemValidationWarning('unit', 'Unit not specified'));
    }

    // Optional: Quantity - warn if missing
    if (defaultQuantity == null || defaultQuantity == 0) {
      warnings.add(ItemValidationWarning('quantity', 'Default quantity not set'));
    }

    // Price validation
    if (unitPrice != null && unitPrice! < 0) {
      errors.add(ItemValidationError('price', 'Price cannot be negative'));
    }
  }

  CatalogItem toCatalogItem({required String companyId, required String userId}) {
    final now = DateTime.now();
    return CatalogItem(
      id: '', // Will be generated by Firestore
      companyId: companyId,
      description: description.trim(),
      sku: sku?.isEmpty ?? true ? null : sku?.trim(),
      unit: unit?.isEmpty ?? true ? null : unit?.trim(),
      defaultQuantity: defaultQuantity ?? 0,
      unitPrice: unitPrice,
      category: category,
      isActive: true,
      usageCount: 0,
      lastUsed: null,
      createdAt: now,
      createdBy: userId,
      updatedAt: now,
      updatedBy: userId,
    );
  }
}

class ItemValidationError {
  final String field;
  final String message;

  ItemValidationError(this.field, this.message);
}

class ItemValidationWarning {
  final String field;
  final String message;

  ItemValidationWarning(this.field, this.message);
}

class _BulkItemCreationScreenState extends State<BulkItemCreationScreen> {
  List<EditableItem>? _editableItems;
  bool _isCreating = false;
  bool _isInitialized = false;
  Set<String> _existingSKUs = {};

  // Pagination
  int _currentPage = 0;
  static const int _rowsPerPage = 50;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _initializeProvider();
    });
  }

  Future<void> _initializeProvider() async {
    try {
      final authProvider = context.read<AuthProvider>();
      final companyId = authProvider.currentUser?.companyId;

      if (companyId != null && companyId.isNotEmpty) {
        final catalogProvider = context.read<CatalogProvider>();
        await catalogProvider.initialize(companyId);
        if (mounted) {
          setState(() => _isInitialized = true);
          _loadExistingSKUs();
          _initializeEmptyTable();
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Error: No company ID found. Please log in again.'),
              backgroundColor: AppTheme.errorColor,
            ),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error initializing: $e'),
            backgroundColor: AppTheme.errorColor,
          ),
        );
      }
    }
  }

  void _loadExistingSKUs() {
    try {
      final catalogProvider = context.read<CatalogProvider>();
      final skus = <String>{};
      for (var item in catalogProvider.allItems) {
        if (item.sku != null && item.sku!.isNotEmpty) {
          skus.add(item.sku!);
        }
      }
      setState(() {
        _existingSKUs = skus;
      });
    } catch (e) {
      debugPrint('Error loading existing SKUs: $e');
    }
  }

  void _initializeEmptyTable() {
    setState(() {
      _editableItems = [
        _createBlankItem(1),
        _createBlankItem(2),
        _createBlankItem(3),
      ];
    });
  }

  EditableItem _createBlankItem(int rowNumber) {
    return EditableItem(
      rowNumber: rowNumber,
      description: '',
      sku: null,
      category: ItemCategory.general,
      unit: null,
      defaultQuantity: null,
      unitPrice: null,
      isSelected: false,
      isRemoved: false,
      isEdited: false,
      errors: [],
      warnings: [],
    );
  }

  void _addRow() {
    if (_editableItems == null) return;

    final maxRow = _editableItems!.fold<int>(
      0,
      (max, i) => i.rowNumber > max ? i.rowNumber : max,
    );

    setState(() {
      _editableItems!.add(_createBlankItem(maxRow + 1));
      _currentPage = (_editableItems!.length / _rowsPerPage).ceil() - 1;
    });
  }

  void _addMultipleRows(int count) {
    if (_editableItems == null) return;

    final maxRow = _editableItems!.fold<int>(
      0,
      (max, i) => i.rowNumber > max ? i.rowNumber : max,
    );

    setState(() {
      for (int i = 0; i < count; i++) {
        _editableItems!.add(_createBlankItem(maxRow + i + 1));
      }
      _currentPage = (_editableItems!.length / _rowsPerPage).ceil() - 1;
    });
  }

  Future<void> _pasteFromClipboard() async {
    try {
      final clipboardData = await Clipboard.getData(Clipboard.kTextPlain);
      if (clipboardData?.text == null) {
        // ignore: use_build_context_synchronously
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('No text in clipboard'),
            backgroundColor: Colors.orange,
          ),
        );
        return;
      }

      // Parse tab-separated or comma-separated values
      final lines = clipboardData!.text!.split('\n');
      final rows = <List<String>>[];

      for (final line in lines) {
        if (line.trim().isEmpty) continue;

        // Try tab-separated first, then comma
        final parts = line.contains('\t') ? line.split('\t') : line.split(',');
        rows.add(parts.map((p) => p.trim()).toList());
      }

      if (rows.isEmpty) {
        // ignore: use_build_context_synchronously
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('No data found in clipboard'),
            backgroundColor: Colors.orange,
          ),
        );
        return;
      }

      // Map columns: Description, SKU, Category, Unit, Quantity, Price
      final maxRow = _editableItems!.fold<int>(
        0,
        (max, i) => i.rowNumber > max ? i.rowNumber : max,
      );

      final newItems = <EditableItem>[];
      for (int i = 0; i < rows.length; i++) {
        final row = rows[i];
        final item = EditableItem(
          rowNumber: maxRow + i + 1,
          description: row.isNotEmpty ? row[0] : '',
          sku: row.length > 1 && row[1].isNotEmpty ? row[1] : null,
          category: _parseCategory(row.length > 2 ? row[2] : ''),
          unit: row.length > 3 && row[3].isNotEmpty ? row[3] : null,
          defaultQuantity: row.length > 4 ? double.tryParse(row[4]) : null,
          unitPrice: row.length > 5 ? double.tryParse(row[5]) : null,
          isSelected: false,
          isRemoved: false,
          isEdited: false,
          errors: [],
          warnings: [],
        );
        newItems.add(item);
      }

      setState(() {
        _editableItems!.addAll(newItems);
        _currentPage = (_editableItems!.length / _rowsPerPage).ceil() - 1;
      });

      _revalidateAll();

      if (!mounted) return;
      // ignore: use_build_context_synchronously
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('✓ Pasted ${newItems.length} rows from clipboard'),
          backgroundColor: AppTheme.successColor,
        ),
      );
    } catch (e) {
      // ignore: use_build_context_synchronously
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error pasting data: $e'),
          backgroundColor: AppTheme.errorColor,
        ),
      );
    }
  }

  ItemCategory _parseCategory(String categoryStr) {
    final lower = categoryStr.toLowerCase().trim();
    for (final category in ItemCategory.values) {
      if (category.toString().contains(lower)) {
        return category;
      }
    }
    return ItemCategory.general;
  }

  void _revalidateAll() {
    if (_editableItems == null) return;

    setState(() {
      for (var item in _editableItems!) {
        item.validate(existingSKUs: _existingSKUs.toList());
      }
    });
  }

  void _toggleAllSelections(bool selected) {
    if (_editableItems == null) return;

    setState(() {
      for (var item in _editableItems!) {
        if (!item.isRemoved && item.isValid) {
          item.isSelected = selected;
        }
      }
    });
  }

  void _removeRow(EditableItem item) {
    if (_editableItems == null) return;

    setState(() {
      _editableItems!.removeWhere((i) => i.rowNumber == item.rowNumber);
      _revalidateAll();
    });
  }

  Future<void> _createItems() async {
    if (_editableItems == null) return;

    final selectedValid = _editableItems!
        .where((i) => i.isSelected && i.isValid && !i.isRemoved)
        .toList();

    if (selectedValid.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('No valid items selected for creation'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }

    final confirm = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Confirm Creation'),
        content: Text(
          'Create ${selectedValid.length} new catalog items?\n\n'
          'This will add new items to the product catalog.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(context, true),
            child: const Text('Create'),
          ),
        ],
      ),
    );

    if (confirm != true) return;

    // ignore: use_build_context_synchronously
    final authProvider = context.read<AuthProvider>();
    // ignore: use_build_context_synchronously
    final catalogProvider = context.read<CatalogProvider>();

    final companyId = authProvider.currentUser?.companyId;
    final userId = authProvider.currentUser?.id;
    if (companyId == null || userId == null) throw Exception('User not found');

    setState(() {
      _isCreating = true;
    });

    try {
      if (!mounted) return;

      final itemsToCreate = selectedValid
          .map((i) => i.toCatalogItem(companyId: companyId, userId: userId))
          .toList();

      // Create each item in the catalog
      for (final item in itemsToCreate) {
        await catalogProvider.addItem(companyId, item);
      }

      // Reload existing SKUs
      _loadExistingSKUs();

      // Save count before clearing state
      final createdCount = selectedValid.length;

      setState(() {
        _isCreating = false;
        _editableItems = [
          _createBlankItem(1),
          _createBlankItem(2),
          _createBlankItem(3),
        ];
        _currentPage = 0;
      });

      if (!mounted) return;

      // Show success
      // ignore: use_build_context_synchronously
      await showDialog(
        context: context,
        builder: (context) => AlertDialog(
          title: const Text('Creation Complete'),
          content: Text(
            'Successfully created $createdCount items!',
          ),
          actions: [
            ElevatedButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('OK'),
            ),
          ],
        ),
      );
    } catch (e) {
      setState(() {
        _isCreating = false;
      });
      if (!mounted) return;
      // ignore: use_build_context_synchronously
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error creating items: $e'),
          backgroundColor: AppTheme.errorColor,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Items'),
        backgroundColor: AppTheme.primaryColor,
        foregroundColor: Colors.white,
        actions: [
          if (_editableItems != null) ...[
            IconButton(
              icon: const Icon(Icons.refresh),
              onPressed: _revalidateAll,
              tooltip: 'Re-validate all',
            ),
          ],
          IconButton(
            icon: const Icon(Icons.help_outline),
            onPressed: () => _showHelp(),
            tooltip: 'Help',
          ),
        ],
      ),
      body: !_isInitialized
          ? const Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(),
                  SizedBox(height: 16),
                  Text('Loading catalog...'),
                ],
              ),
            )
          : _editableItems == null
              ? const Center(child: CircularProgressIndicator())
              : _buildEditableTable(),
    );
  }

  Widget _buildEditableTable() {
    final items = _editableItems!;
    final totalCount = items.length;
    final selectedCount = items.where((i) => i.isSelected && !i.isRemoved).length;
    final validCount = items.where((i) => i.isValid && !i.isRemoved).length;
    final errorCount = items.where((i) => i.hasErrors && !i.isRemoved).length;
    final warningCount = items.where((i) => !i.isRemoved).fold<int>(0, (total, i) => total + i.warnings.length);

    final totalPages = (totalCount / _rowsPerPage).ceil();
    final startIndex = _currentPage * _rowsPerPage;
    final endIndex = (startIndex + _rowsPerPage).clamp(0, totalCount);
    final pageItems = items.sublist(startIndex, endIndex);

    return Column(
      children: [
        // Summary header
        Container(
          padding: const EdgeInsets.all(16),
          color: errorCount > 0 ? Colors.red[50] : Colors.green[50],
          child: Column(
            children: [
              Row(
                children: [
                  Icon(
                    errorCount > 0 ? Icons.warning : Icons.check_circle,
                    color: errorCount > 0 ? AppTheme.errorColor : AppTheme.successColor,
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'New Catalog Items',
                          style: TextStyle(fontWeight: FontWeight.bold),
                        ),
                        Text(
                          '$totalCount rows • $validCount valid • $errorCount errors • $warningCount warnings',
                          style: const TextStyle(fontSize: 12),
                        ),
                      ],
                    ),
                  ),
                  PopupMenuButton<String>(
                    itemBuilder: (context) => <PopupMenuEntry<String>>[
                      const PopupMenuItem<String>(
                        enabled: false,
                        child: Text('Add Rows', style: TextStyle(fontWeight: FontWeight.bold)),
                      ),
                      PopupMenuItem<String>(
                        child: const Text('Add 1 Row'),
                        onTap: () => _addRow(),
                      ),
                      PopupMenuItem<String>(
                        child: const Text('Add 5 Rows'),
                        onTap: () => _addMultipleRows(5),
                      ),
                      PopupMenuItem<String>(
                        child: const Text('Add 10 Rows'),
                        onTap: () => _addMultipleRows(10),
                      ),
                      const PopupMenuDivider(),
                      PopupMenuItem<String>(
                        child: const Text('Paste from Clipboard'),
                        onTap: () => _pasteFromClipboard(),
                      ),
                    ],
                    child: OutlinedButton.icon(
                      onPressed: null,
                      icon: const Icon(Icons.add, size: 16),
                      label: const Text('Add Rows'),
                    ),
                  ),
                  const SizedBox(width: 8),
                  if (validCount > 0)
                    ElevatedButton.icon(
                      onPressed: _isCreating ? null : _createItems,
                      icon: _isCreating
                          ? const SizedBox(
                              width: 16,
                              height: 16,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            )
                          : const Icon(Icons.check),
                      label: Text(_isCreating
                          ? 'Creating...'
                          : 'Create Selected ($selectedCount)'),
                    ),
                ],
              ),
              const SizedBox(height: 8),
              Row(
                children: [
                  Checkbox(
                    value: selectedCount == validCount && validCount > 0,
                    tristate: selectedCount > 0 && selectedCount < validCount,
                    onChanged: validCount > 0
                        ? (value) => _toggleAllSelections(value ?? false)
                        : null,
                  ),
                  const Text('Select all valid rows'),
                ],
              ),
            ],
          ),
        ),

        // Editable table
        Expanded(
          child: SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: SizedBox(
              width: 1300,
              child: Column(
                children: [
                  Container(
                    color: Colors.grey[200],
                    padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 8),
                    child: const Row(
                      children: [
                        SizedBox(width: 40),
                        SizedBox(width: 50, child: Text('Row', style: TextStyle(fontWeight: FontWeight.bold))),
                        SizedBox(width: 200, child: Text('Description', style: TextStyle(fontWeight: FontWeight.bold))),
                        SizedBox(width: 120, child: Text('SKU', style: TextStyle(fontWeight: FontWeight.bold))),
                        SizedBox(width: 120, child: Text('Category', style: TextStyle(fontWeight: FontWeight.bold))),
                        SizedBox(width: 100, child: Text('Unit', style: TextStyle(fontWeight: FontWeight.bold))),
                        SizedBox(width: 120, child: Text('Default Qty', style: TextStyle(fontWeight: FontWeight.bold))),
                        SizedBox(width: 120, child: Text('Unit Price', style: TextStyle(fontWeight: FontWeight.bold))),
                        SizedBox(width: 80, child: Text('Actions', style: TextStyle(fontWeight: FontWeight.bold))),
                      ],
                    ),
                  ),

                  Expanded(
                    child: ListView.builder(
                      itemCount: pageItems.length,
                      itemBuilder: (context, index) {
                        final item = pageItems[index];
                        return _buildEditableRow(item);
                      },
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),

        // Pagination
        if (totalPages > 1)
          Container(
            padding: const EdgeInsets.all(16),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                IconButton(
                  icon: const Icon(Icons.chevron_left),
                  onPressed: _currentPage > 0
                      ? () => setState(() => _currentPage--)
                      : null,
                ),
                Text(
                  'Page ${_currentPage + 1} of $totalPages',
                  style: const TextStyle(fontWeight: FontWeight.bold),
                ),
                IconButton(
                  icon: const Icon(Icons.chevron_right),
                  onPressed: _currentPage < totalPages - 1
                      ? () => setState(() => _currentPage++)
                      : null,
                ),
                const SizedBox(width: 16),
                Text('Showing ${startIndex + 1}-$endIndex of $totalCount'),
              ],
            ),
          ),
      ],
    );
  }

  Widget _buildEditableRow(EditableItem item) {
    final hasErrors = item.hasErrors;
    final hasWarnings = item.hasWarnings;
    final rowColor = hasErrors
        ? Colors.red[50]
        : hasWarnings
            ? Colors.orange[50]
            : item.isEdited
                ? Colors.blue[50]
                : Colors.white;

    return Container(
      decoration: BoxDecoration(
        color: rowColor,
        border: Border(bottom: BorderSide(color: Colors.grey[300]!)),
      ),
      padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 8),
      child: Row(
        children: [
          SizedBox(
            width: 40,
            child: Checkbox(
              value: item.isSelected,
              onChanged: item.isValid
                  ? (value) {
                      setState(() {
                        item.isSelected = value ?? false;
                      });
                    }
                  : null,
            ),
          ),

          SizedBox(
            width: 50,
            child: Row(
              children: [
                if (hasErrors)
                  const Icon(Icons.error, color: Colors.red, size: 16)
                else if (hasWarnings)
                  const Icon(Icons.warning, color: Colors.orange, size: 16),
                const SizedBox(width: 4),
                Text('#${item.rowNumber}'),
              ],
            ),
          ),

          SizedBox(
            width: 200,
            child: _buildEditableCell(
              value: item.description,
              onChanged: (value) {
                setState(() {
                  item.description = value;
                  item.isEdited = true;
                  item.validate(existingSKUs: _existingSKUs.toList());
                });
              },
              hasError: item.errors.any((e) => e.field == 'description'),
            ),
          ),

          SizedBox(
            width: 120,
            child: _buildEditableCell(
              value: item.sku ?? '',
              onChanged: (value) {
                setState(() {
                  item.sku = value.isEmpty ? null : value;
                  item.isEdited = true;
                  item.validate(existingSKUs: _existingSKUs.toList());
                });
              },
            ),
          ),

          SizedBox(
            width: 120,
            child: DropdownButton<ItemCategory>(
              value: item.category,
              onChanged: (value) {
                if (value != null) {
                  setState(() {
                    item.category = value;
                    item.isEdited = true;
                  });
                }
              },
              items: ItemCategory.values
                  .map((category) => DropdownMenuItem(
                        value: category,
                        child: Text(category.displayName, style: const TextStyle(fontSize: 14)),
                      ))
                  .toList(),
              isExpanded: true,
              underline: Container(),
            ),
          ),

          SizedBox(
            width: 100,
            child: _buildEditableCell(
              value: item.unit ?? '',
              onChanged: (value) {
                setState(() {
                  item.unit = value.isEmpty ? null : value;
                  item.isEdited = true;
                  item.validate(existingSKUs: _existingSKUs.toList());
                });
              },
            ),
          ),

          SizedBox(
            width: 120,
            child: _buildEditableCell(
              value: item.defaultQuantity?.toString() ?? '',
              onChanged: (value) {
                setState(() {
                  item.defaultQuantity = value.isEmpty ? null : double.tryParse(value);
                  item.isEdited = true;
                  item.validate(existingSKUs: _existingSKUs.toList());
                });
              },
            ),
          ),

          SizedBox(
            width: 120,
            child: _buildEditableCell(
              value: item.unitPrice?.toStringAsFixed(2) ?? '',
              onChanged: (value) {
                setState(() {
                  item.unitPrice = value.isEmpty ? null : double.tryParse(value);
                  item.isEdited = true;
                  item.validate(existingSKUs: _existingSKUs.toList());
                });
              },
            ),
          ),

          SizedBox(
            width: 80,
            child: Row(
              children: [
                if (hasErrors || hasWarnings)
                  IconButton(
                    icon: const Icon(Icons.info_outline, size: 20),
                    onPressed: () => _showErrorsDialog(item),
                    tooltip: 'View errors/warnings',
                  ),
                IconButton(
                  icon: const Icon(Icons.delete_outline, size: 20),
                  onPressed: () => _removeRow(item),
                  tooltip: 'Delete row',
                  color: Colors.red,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildEditableCell({
    required String value,
    required ValueChanged<String> onChanged,
    bool hasError = false,
  }) {
    return TextFormField(
      initialValue: value,
      decoration: InputDecoration(
        isDense: true,
        contentPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 8),
        border: OutlineInputBorder(
          borderSide: BorderSide(color: hasError ? Colors.red : Colors.grey[300]!),
        ),
        enabledBorder: OutlineInputBorder(
          borderSide: BorderSide(color: hasError ? Colors.red : Colors.grey[300]!),
        ),
      ),
      onChanged: onChanged,
      style: const TextStyle(fontSize: 14),
    );
  }

  void _showErrorsDialog(EditableItem item) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Row #${item.rowNumber} - Issues'),
        content: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              if (item.errors.isNotEmpty) ...[
                const Text(
                  'Errors:',
                  style: TextStyle(fontWeight: FontWeight.bold, color: Colors.red),
                ),
                const SizedBox(height: 8),
                ...item.errors.map((error) => Padding(
                      padding: const EdgeInsets.only(bottom: 4),
                      child: Text('• ${error.message}', style: const TextStyle(color: Colors.red)),
                    )),
                const SizedBox(height: 16),
              ],
              if (item.warnings.isNotEmpty) ...[
                const Text(
                  'Warnings:',
                  style: TextStyle(fontWeight: FontWeight.bold, color: Colors.orange),
                ),
                const SizedBox(height: 8),
                ...item.warnings.map((warning) => Padding(
                      padding: const EdgeInsets.only(bottom: 4),
                      child: Text('• ${warning.message}', style: const TextStyle(color: Colors.orange)),
                    )),
              ],
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }

  void _showHelp() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Item Creation Help'),
        content: const SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                'How to create items:',
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              Text('1. Add rows manually or paste from clipboard'),
              Text('2. Fill in item data in the table'),
              Text('3. Review validation results'),
              Text('4. Select rows to create'),
              Text('5. Click "Create Selected"'),
              SizedBox(height: 16),
              Text(
                'Quick Entry:',
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              Text('• Click "Add Rows" to add blank rows'),
              Text('• Paste multi-row data: [Description][Tab][SKU][Tab][Category]...'),
              SizedBox(height: 16),
              Text(
                'Visual Indicators:',
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              Text('• Red rows have errors (cannot create)'),
              Text('• Orange rows have warnings (can still create)'),
              Text('• Blue rows have been edited'),
              SizedBox(height: 16),
              Text(
                'Required Fields:',
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              Text('• Description (required for all items)'),
              Text('• Everything else is optional'),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }
}
